######################################################################
# Automatically generated by qmake (2.00a) ti 8. mar 16:20:21 2005
######################################################################

CONFIG += testcase
TARGET = tst_qstyleoption
TEMPLATE = app
QT += widgets testlib
# Input
SOURCES += tst_qstyleoption.cpp


