######################################################################
# Automatically generated by qmake (2.00a) ti 8. mar 16:20:21 2005
######################################################################

load(qttest_p4)
TEMPLATE = app

# Input
SOURCES += tst_qstyleoption.cpp


