QT_CORE_VERSION = $$QT_VERSION
QT_CORE_MAJOR_VERSION = $$QT_MAJOR_VERSION
QT_CORE_MINOR_VERSION = $$QT_MINOR_VERSION
QT_CORE_PATCH_VERSION = $$QT_PATCH_VERSION

QT.core.name = QtCore
QT.core.includes = $$QT_MODULE_INCLUDE_BASE/QtCore
QT.core.libs = $$QT_MODULE_LIB_BASE
QT.core.depends =

QT_CONFIG += core
