QT_GUI_VERSION = $$QT_VERSION
QT_GUI_MAJOR_VERSION = $$QT_MAJOR_VERSION
QT_GUI_MINOR_VERSION = $$QT_MINOR_VERSION
QT_GUI_PATCH_VERSION = $$QT_PATCH_VERSION

QT.gui.name = QtGui
QT.gui.includes = $$QT_MODULE_INCLUDE_BASE/QtGui
QT.gui.libs = $$QT_MODULE_LIB_BASE
QT.gui.depends = core network

QT_CONFIG += gui
