QT_CORE_VERSION = $$QT_VERSION
QT_NETWORK_MAJOR_VERSION = $$QT_MAJOR_VERSION
QT_NETWORK_MINOR_VERSION = $$QT_MINOR_VERSION
QT_NETWORK_PATCH_VERSION = $$QT_PATCH_VERSION

QT.network.name = QtNetwork
QT.network.includes = $$QT_MODULE_INCLUDE_BASE/QtNetwork
QT.network.libs = $$QT_MODULE_LIB_BASE
QT.network.depends = core
