QT_OPENVG_VERSION = $$QT_VERSION
QT_OPENVG_MAJOR_VERSION = $$QT_MAJOR_VERSION
QT_OPENVG_MINOR_VERSION = $$QT_MINOR_VERSION
QT_OPENVG_PATCH_VERSION = $$QT_PATCH_VERSION

QT.openvg.name = QtOpenVG
QT.openvg.includes = $$QT_MODULE_INCLUDE_BASE/QtOpenVG
QT.openvg.libs = $$QT_MODULE_LIB_BASE
QT.openvg.depends = core gui
QT.openvg.CONFIG = openvg

QT_CONFIG += openvg
