QT_SQL_VERSION = $$QT_VERSION
QT_SQL_MAJOR_VERSION = $$QT_MAJOR_VERSION
QT_SQL_MINOR_VERSION = $$QT_MINOR_VERSION
QT_SQL_PATCH_VERSION = $$QT_PATCH_VERSION

QT.sql.name = QtSql
QT.sql.includes = $$QT_MODULE_INCLUDE_BASE/QtSql
QT.sql.sources = $$QT_MODULE_BASE/src/sql
QT.sql.libs = $$QT_MODULE_LIB_BASE
QT.sql.depends = core
