QT_XML_VERSION = $$QT_VERSION
QT_XML_MAJOR_VERSION = $$QT_MAJOR_VERSION
QT_XML_MINOR_VERSION = $$QT_MINOR_VERSION
QT_XML_PATCH_VERSION = $$QT_PATCH_VERSION

QT.xml.name = QtXml
QT.xml.includes = $$QT_MODULE_INCLUDE_BASE/QtXml
QT.xml.private_includes = $$QT_MODULE_INCLUDE_BASE/QtXml/private
QT.xml.sources = $$QT_MODULE_BASE/src/xml
QT.xml.libs = $$QT_MODULE_LIB_BASE
QT.xml.depends = core
