######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 15 13:45:41 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= app_bundle debug_and_release
DESTDIR=.
QT -= gui
wince*: {
   LIBS += coredll.lib
}
# Input
HEADERS += signalbug.h
SOURCES += signalbug.cpp


