TEMPLATE=subdirs
SUBDIRS=\
    qalgorithms \
    qarraydata \
    qbitarray \
    qbytearray \
    qbytearraymatcher \
    qbytedatabuffer \
    qcache \
    qchar \
    qcollator \
    qcommandlineparser \
    qcontiguouscache \
    qcryptographichash \
    qdate \
    qdatetime \
    qeasingcurve \
    qelapsedtimer \
    qexplicitlyshareddatapointer \
    qfreelist \
    qhash \
    qline \
    qlinkedlist \
    qlist \
    qlocale \
    qmap \
    qmargins \
    qmessageauthenticationcode \
    qpair \
    qpoint \
    qpointf \
    qqueue \
    qrect \
    qregexp \
    qregularexpression \
    qringbuffer \
    qscopedpointer \
    qscopedvaluerollback \
    qset \
    qsharedpointer \
    qsize \
    qsizef \
    qstl \
    qstring \
    qstring_no_cast_from_bytearray \
    qstringbuilder \
    qstringlist \
    qstringmatcher \
    qstringref \
    qtextboundaryfinder \
    qtime \
    qtimezone \
    qtimeline \
    qvarlengtharray \
    qvector
