#Staging tests for gui
TEMPLATE = subdirs

SUBDIRS += modeltest \
    qabstractbutton \
    qabstractitemmodel \
    qabstractprintdialog \
    qabstractproxymodel \
    qabstractslider \
    qabstractspinbox \
    qabstracttextdocumentlayout \
    qabstractvideobuffer \
    qabstractvideosurface \
    qaction \
    qfileiconprovider \
    qfocusframe \
    qfont \
    qfontmetrics \
    qformlayout \
    qgraphicslayout \
    qnetworkcachemetadata \
    qpaintengine \
    qpalette \
    qparallelanimationgroup \
    qpauseanimation \
    qpicture \
    qplaintextedit \
    qpointer \
    qprinterinfo \
    qprogressbar \
    qprogressdialog \
    qpropertyanimation \
    qradiobutton \
    qregexpvalidator \
    qscriptenginedebugger \
    qscrollarea \
    qscrollbar \
    qsharedpointer_and_qwidget \
    qsignalmapper \
    qslider \
    qsortfilterproxymodel \
    qspinbox \
    qstackedlayout \
    qstackedwidget \
    qstandarditem \
    qstandarditemmodel \
    qstatemachine \
    qstringlistmodel \
    qstyleoption \
    qsyntaxhighlighter \
    qtextblock \
    qtextcursor \
    qtextformat \
    qtextlist \
    qtextobject \
    qtextscriptengine \
    qtexttable \
    qtoolbox \
    qtoolbutton \
    qtreewidgetitemiterator \
    qundogroup \
    qundostack \
    qvideosurfaceformat \
    qwidgetaction
