plugins {
    alias(libs.plugins.android.library)
}

group = 'org.qtproject.qt'

android {
    namespace = 'org.qtproject.qt.android'
    compileSdk = (project.findProperty('compileSdk') ?: '36') as int

    defaultConfig {
        minSdk = (project.findProperty('minSdk') ?: '28') as int
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
        }
    }
}
