#!/bin/sh

FILE="$1"
RES="$FILE"
if [ -z "${FILE##/*}" ]; then
    true
elif [ "$OSTYPE" = "msys" -a -z "${FILE##[a-zA-Z]:[/\\]*}" ]; then
    true
else
    RES="$PWD/$FILE"
fi
RES=$RES/
while true; do
    nres=`echo "$RES" | sed "s,/[^/][^/]*/\.\./,/,g; s,/\./,/,g"`
    test x"$nres" = x"$RES" && break
    RES=$nres
done
RES=`echo "$RES" | sed "s,//,/,g; s,/$,,"`
echo $RES #return

