SUBPROGRAMS = \
     #alive \
     assert \
     badxml \
     benchlibcallgrind \
     benchlibcounting \
     benchlibeventcounter \
     benchliboptions \
     benchlibtickcounter \
     benchlibwalltime \
     cmptest \
     commandlinedata \
     counting \
     crashes \
     datatable \
     datetime \
     differentexec \
     exceptionthrow \
     expectfail \
     failcleanup \
     failinit \
     failinitdata \
     fetchbogus \
     findtestdata \
     float \
     globaldata \
     longstring \
     maxwarnings \
     multiexec \
     printdatatags \
     printdatatagswithglobaltags \
     qexecstringlist \
     singleskip \
     skip \
     skipcleanup \
     skipinit \
     skipinitdata \
     sleep \
     strcmp \
     subtest \
     warnings \
     xunit
