######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 10 17:02:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp\
    tabletwidget.cpp
HEADERS += tabletwidget.h
