// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
// Qt-Security score:critical reason:data-parser
#include "private/qtparsetemporal_p.h"

#include "private/qstringiterator_p.h"
#include "private/qttemporalpattern_p.h"

#include <algorithm> // sort
#include <optional>
#include <utility> // exchange, move
#include <vector>

QT_BEGIN_NAMESPACE

namespace {
using namespace QtParseTemporal;
using namespace QtTemporalPattern;

struct PartialParse
{
    ParsedTemporal results;
    int periodInDay = -1; // 0: am, 1: pm
    int hourMod12 = 0; // 1 through 12
    int yearWithinCentury = -1; // 0 through 99
    enum Flaw : quint16 {
        // Flaws that justify prefering a shorter parse without the flaw over
        // longer with it, in order of decreasing severity:
        Irreconcilable = 1, // field values cannot be reconciled
        // Ideally continuations() would catch irreconcilable issues, but if one
        // is expensive to spot it can be left for resolve() to flag up.

        // Flaws not worth giving up a longer parse over, in decreasing order of
        // strength of preference among those of equal length:
        // None, for now
    };
    Q_DECLARE_FLAGS(Flaws, Flaw)
    Flaws wanton = {};

    // Constructor for initial empty parse:
    PartialParse(qsizetype from) { results.startIndex = results.endIndex = from; }
    // Constructor extending a parse with something more:
    PartialParse(const PartialParse &base, const QtParseCommon::ParsedText &more)
        : PartialParse(base)
    {
        Q_ASSERT(results.endIndex == more.startIndex);
        results.endIndex = more.endIndex;
    }

    Qt::weak_ordering compare(const PartialParse &alt) const noexcept
    {
        // Measures of how this->wanton differs from alt.wanton: it's worse if
        // it has a flaw that alt lacks, better if the opposite. Here, "less" is
        // used to mean "this is better than alt" as we sort better entries
        // earlier in our lists of partial parse candidates.
        const auto order = [better = alt.wanton & ~wanton,
                            worse = wanton & ~alt.wanton](Flaw test) {
            Q_ASSERT(!(worse & better)); // So at most one of these testFlag()s is true:
            if (better.testFlag(test))
                return Qt::weak_ordering::less;
            if (worse.testFlag(test))
                return Qt::weak_ordering::greater;
            return Qt::weak_ordering::equivalent;
        };

        if (auto res = order(Flaw::Irreconcilable); res != 0)
            return res;

        // The above takes precedence over size: a shorter parse without those
        // flaws is better than a longer one with them.

        // Longer is better, to be understood as "sorts before" i.e. less than.
        if (auto res = Qt::compareThreeWay(alt.results.size(), results.size()); res != 0)
            return res;

        // The following remains as a preference only among matches of the same
        // length: it's nice to avoid, but a longer parse is still better.
        // None, for now.

        return Qt::weak_ordering::equivalent;
    }
};
Q_DECLARE_OPERATORS_FOR_FLAGS(PartialParse::Flaws)

std::vector<PartialParse> spacePadExtend(std::vector<PartialParse> &&matched, QStringView text)
{
    // Pass the whole text: the results.endIndex of the last entry in matched is
    // an index into it that we shall use to add entries that extend that entry.
    Q_ASSERT(!matched.empty());
    // Assumes matched.back()'s last field is allowed to end in space-padding
    // and inserts a partial parse resulting from accepting each subsequent
    // space as extending the match. Each longer match is inserted before all
    // shorter matches. Only extensions of matched.back() are added, so call
    // after adding each entry to matched, if adding several.
    const qsizetype position = matched.size() - 1;
    PartialParse copy = matched.back();
    QStringIterator iter(text, copy.results.endIndex);
    while (iter.hasNext() && QChar::isSpace(iter.next())) {
        Q_ASSERT(iter.index() > copy.results.endIndex);
        copy.results.endIndex = iter.index();
        matched.insert(matched.begin() + position, copy);
    }
    return matched;
}

QtParseCommon::ParsedText matchesAt(QStringView text, qsizetype from, const QString &sought,
                                    TemporalFieldFlags flags)
{
    using F = TemporalFieldFlag;
    const bool allowLeadingSpace = flags.testFlag(F::SpacePad);
    Q_ASSERT(sought.size() > 0);
    // Note: returns the first match within text[from:]. If sought is all space
    // and SpacePad is set, there may be later matches if text[from:] starts
    // with more space than (possibly some non-matching spaces, then) that.
    // caller is expected to follow the match implied by the return from this
    // with more generated by spacePadExtend().

    const auto beginLength = [flex = flags.testFlag(F::FlexSpace)]
        (QStringView view, QStringView target, Qt::CaseSensitivity cs = Qt::CaseSensitive) {
        // Technical hitch: case-insensitive comparison may match a string of
        // different length. Roll a brute-force length-determining version:
        const auto matchFront = [cs](QStringView view, QStringView target) {
            if (view.startsWith(target, cs)) {
                qsizetype length = target.size();
                while (view.first(length - 1).startsWith(target, cs))
                    --length;
                while (!view.first(length).startsWith(target, cs))
                    ++length;
                Q_ASSERT(length > 0);
                return length;
            }
            return qsizetype(-1);
        };
        const auto spaceForward = [](QStringIterator &iter) {
            // Steps iter past next non-space, returns index at which it appeared.
            qsizetype used;
            do {
                used = iter.index();
            } while (iter.hasNext() && QChar::isSpace(iter.next()));
            return used;
        };
        constexpr qsizetype failed = 0;
        qsizetype matched = 0;
        if (flex) {
            QStringIterator iter(target);
            while (iter.hasNext()) {
                qsizetype head = iter.index();
                if (QChar::isSpace(iter.next())) {
                    qsizetype same = head > 0 ? matchFront(view, target.first(head)) : 0;
                    if (same < 0)
                        return failed;
                    QStringIterator viter(view, same);
                    // Require at least one spacing character in view to match those in target:
                    if (!viter.hasNext() || !QChar::isSpace(viter.next()))
                        return failed;
                    same = spaceForward(viter);
                    matched += same;
                    view = view.sliced(same);
                    target = target.sliced(spaceForward(iter));
                    iter = QStringIterator(target);
                }
            }
        }
        const qsizetype tail = target.isEmpty() ? 0 : matchFront(view, target);
        if (tail < 0)
            return failed;
        return matched + tail;
    };
    // TODO: consider a comparison that ignores Unicode invisibles, like BiDi
    // markers, when matching.
    qsizetype offset = 0;
    do {
        QStringView view = text.sliced(from + offset);
        if (flags.testFlag(F::IgnoreCase)) {
            if (qsizetype match = beginLength(view, sought, Qt::CaseInsensitive))
                return {from, from + offset + match};
        } else if (flags.testAnyFlags(F::LowerCase | F::UpperCase)) {
            // If either case is specified, only match specified cases.
            // If both cases are specified, accept either (but not mixed).
            if (flags.testFlag(F::LowerCase)) {
                if (qsizetype match = beginLength(view, sought.toLower()))
                    return {from, from + offset + match};
            }
            if (flags.testFlag(F::UpperCase)) {
                if (qsizetype match = beginLength(view, sought.toUpper()))
                    return {from, from + offset + match};
            }
            // Otherwise, only an exact match is accepted:
        } else if (qsizetype match = beginLength(view, sought)) {
            return {from, from + offset + match};
        }

        // No match at this position; maybe later if leading space is allowed:
        if (!allowLeadingSpace) {
            Q_ASSERT(!offset);
            break;
        }

        // Consume one space at a time until we find a match:
        QStringIterator iter(text.sliced(from), offset);
        if (!iter.hasNext() || !QChar::isSpace(iter.next()))
            break;

        Q_ASSERT(iter.index() > offset);
        offset = iter.index();
    } while (text.size() >= offset + sought.size() / 2);
    // Loop wants to test text.size() >= offset + sought.size(), but see beginLength().
    return {};
}

bool longerEarlier(const PartialParse &left, const PartialParse &right)
{
    // True if we want left before right in our sorted lists.
    // We want longer matches before shorter:
    return left.results.endIndex > right.results.endIndex;
}

template <typename Action>
void forEachLocaleFormat(TemporalFieldFlags flags, Action action)
{
    using Flag = TemporalFieldFlag;
    constexpr auto Widths = FieldGroup::WidthMask;
    if (matchesFlagWithin(flags, Flag::Wide, Widths))
        action(QLocale::LongFormat);
    if (matchesFlagsWithin(flags, Flag::Short | Flag::Abbreviated, Widths))
        action(QLocale::ShortFormat);
    if (matchesFlagWithin(flags, Flag::Narrow, Widths))
        action(QLocale::NarrowFormat);
}

class TemporalFieldMatcher
{
    const QLocale locale;
    const QCalendar calendar;
    const std::optional<int> baseYear;

    std::vector<PartialParse> dayNameExtend(const PartialParse &base, QStringView text,
                                            TemporalFieldFlags flags) const;
public:
    TemporalFieldMatcher(const QLocale &loc, QCalendar cal, std::optional<int> centuryStart)
        : locale(loc), calendar(cal), baseYear(centuryStart)
    {}

    std::vector<PartialParse> continuations(const PartialParse &base, QStringView text,
                                            const TemporalField &field) const;
    bool isSelfConsistent(const PartialParse &parsed, TemporalFieldCategory category) const;
    bool resolve(PartialParse &parsed) const;
};

bool TemporalFieldMatcher::isSelfConsistent(const PartialParse &, TemporalFieldCategory) const
{
    // Take into account calendar, and potentially baseYear, but only do cheap
    // checks. This will be run on *each* candidate parse after *each* field,
    // need not check conditions the current field could not have affected.
    return true;
}

bool TemporalFieldMatcher::resolve(PartialParse &) const
{
    // Final pass, modifying parsed as needed, true if parse.result has been
    // given a value consistent with all fields of parse. Applies fully rigorous
    // checks, given what isSelfConsistent() already checked. May record flaws
    // in parse.wanton where relevant tests reveal them.
    return true;
}

std::vector<PartialParse>
TemporalFieldMatcher::dayNameExtend(const PartialParse &base, QStringView text,
                                    TemporalFieldFlags flags) const
{
    std::vector<PartialParse> matches;
    using Flag = TemporalFieldFlag;

    auto addIfMatch = [&matches, base, text, flags](int dow, QString &&name) {
        // tryEachDayOfWeek() has ensured this:
        Q_ASSERT(!base.results.dayOfWeek || base.results.dayOfWeek == dow);
        if (name.isEmpty()) // Locale doesn't know this day of the week's name.
            return;
        // If matchesAt(), add to matches:
        auto match = matchesAt(text, base.results.endIndex, name, flags);
        if (match) {
            PartialParse grow(base,match);
            grow.results.dayOfWeek = dow;
            matches.push_back(grow);
            if (flags.testFlag(Flag::SpacePad))
                matches = spacePadExtend(std::move(matches), text);
        }
    };

    constexpr auto Forms = FieldGroup::FormMask;
    const bool verb = matchesFlagWithin(flags, Flag::Verbal, Forms);
    const bool lone = matchesFlagWithin(flags, Flag::Standalone, Forms);
    auto tryEachNameType = [this, addIfMatch, verb, lone](QLocale::FormatType form, int dow) {
        if (lone)
            addIfMatch(dow, calendar.standaloneWeekDayName(locale, dow, form));
        if (verb)
            addIfMatch(dow, calendar.weekDayName(locale, dow, form));
    };

    auto tryEachDayOfWeek = [dow = base.results.dayOfWeek,
                             tryEachNameType](QLocale::FormatType form) {
        if (dow > 0) {
            tryEachNameType(form, dow);
        } else {
            // Iterate possible day numbers. Issue: some calendars might have
            // intercalary days with numbers > 7. When that happens, we may
            // need to let this run past 7 until it's seen some empty answers.
            for (int i = 1; i <= 7; ++i)
                tryEachNameType(form, i);
        }
    };
    forEachLocaleFormat(flags, tryEachDayOfWeek);

    std::sort(matches.begin(), matches.end(), longerEarlier);
    return matches;
}

/*!
    \internal
    Find all matches to \a field, within \a text, that extend \a base.

    Each match must begin at offset \c{base.results.endIndex} within \a text.
    For each match, update a copy of \a base with the match's result, to include
    in the returned list.

    May use \c calendar to determine the range of values allowed for field.
    Does not attempt to determine consistency between fields; see resolve() and
    isSelfConsistent() for that. Updates the copy's member holding the value
    described by \a field to reflect the match.

    Ignores base.result.startIndex and base.result.bounds and updates each
    copy's .endIndex to reflect the end of the match. (This leaves the caller to
    decide whether to transfer that to .bounds.)

    For fields that allow space padding, this consumes leading space as
    necessary to make a match and includes a match for each end position at
    which it could end; before any dangling space and after each space that
    follows. Later calls to \c continuations() shall filter out any earlier
    matches that precludes later fields matching just after its end. Successive
    space-padded fields surrounded by large amounts of space are apt to lead to
    many matches, as are final space-padded fields followed by large amounts of
    space. (TODO: we can almost certainly mitigate this with a trivial
    heuristic, once everything is working.)

    For those matches with various flaws, relative to the field specification
    (such as using zero padding when not obliged to), the copy's .wanton records
    that flaw.

    Sort order of the returned list should put entries likely to represent more
    suitable matches (ignoring .wanton complications) earlier. For most fields,
    that means longer matches come first. (For full year field matches with > 4
    digits, though, that reverses.)
*/
std::vector<PartialParse>
TemporalFieldMatcher::continuations(const PartialParse &base, QStringView text,
                                    const TemporalField &field) const
{
    std::vector<PartialParse> matches;
    switch (field.category) {
        using Cat = TemporalFieldCategory;
        using Flag = TemporalFieldFlag;
    case Cat::Literal:
        if (auto match = matchesAt(text, base.results.endIndex, field.literal, field.options)) {
            matches.push_back(PartialParse(base, match));
            if (field.options.testFlag(Flag::SpacePad))
                matches = spacePadExtend(std::move(matches), text);
        }
        break;
    case Cat::TimeZone:
        break;

        // case Cat::MillisecondInDay: break;
    case Cat::SecondFraction:
        break;
    case Cat::Second:
        break;
        // case Cat::MinuteFraction: break;
    case Cat::Minute:
        break;
        // case Cat::HourFraction: break;
    case Cat::HourMod12:
        break;
    case Cat::Hour:
        break;
    case Cat::PeriodInDay: // am/pm; LDML also has noon, midnight, "at night" and others.
        break;

    case Cat::DayOfWeek:
        matches = dayNameExtend(base, text, field.options);
        break;
    case Cat::DayOfMonth:
        break;
        // case Cat::DayOfYear: break;
        // case Cat::JulianDay: break;
        // case Cat::WeekOfMonth: break;
        // case Cat::WeekOfYear: break;
    case Cat::Month:
        break;
        // case Cat::Quarter: break;
    case Cat::YearWithinCentury:
        break;
    case Cat::Year:
        break;
        // case Cat::RelatedGregorianYear: break;
        // case Cat::Century: break;
        // case Cat::Era: break;
    }
    return matches;
}

} // nameless namespace

namespace QtParseTemporal {
QDate ParsedTemporal::date(QCalendar cal, QDate defaults) const
{
    if (defaults.isValid()) {
        return QDate(year ? *year : defaults.year(cal), month ? month : defaults.month(cal),
                     dayOfMonth ? dayOfMonth : defaults.day(cal), cal);
    }
    if (year && month && dayOfMonth)
        return QDate(*year, month, dayOfMonth, cal);
    return {};
}

QTime ParsedTemporal::time(QTime defaults) const
{
    if (defaults.isValid()) {
        return QTime(hour < 0 ? defaults.hour() : hour,
                     minute < 0 ? defaults.minute() : minute,
                     second < 0 ? defaults.second() : second,
                     millis < 0 ? defaults.msec() : millis);
    }

    if (hour < 0 || hour > 24)
        return {};
    if (minute < 0)
        return QTime(hour, 0);
    if (second < 0)
        return QTime(hour, minute);
    if (millis < 0)
        return QTime(hour, minute, second);
    return QTime(hour, minute, second, millis);
}

ParsedTemporal prefix(QStringView text, QSpan<const QtTemporalPattern::TemporalField> fields,
                      const QLocale &locale, QCalendar cal,
                      std::optional<int> baseYear, qsizetype from)
{
    if (from < 0 || from >= text.size())
        return {};

    const TemporalFieldMatcher matcher(locale, cal, baseYear);
    // Technically this is the correct (empty) result when fields.isEmpty():
    std::vector<PartialParse> maybe{PartialParse(from)};

    qsizetype toCome = fields.size();
    for (const QtTemporalPattern::TemporalField &field : fields) {
        --toCome;
        const std::vector<PartialParse> prior = std::exchange(maybe, {});
        for (const PartialParse &base : prior) {
            std::vector<PartialParse> more
                = matcher.continuations(base, text, field);
            for (PartialParse &candidate : more) {
                // Consistency won't have been changed by a literal field:
                if ((field.category == TemporalFieldCategory::Literal
                     || matcher.isSelfConsistent(candidate, field.category))) {
                    if (toCome) // Earlier fields' ends go in bounds:
                        candidate.results.bounds.push_back(candidate.results.endIndex);
                    else if (!matcher.resolve(candidate)) // Last field: makes sense of it all.
                        continue;
                    maybe.push_back(std::move(candidate));
                }
            }
        }
        if (maybe.empty()) // No point continuing
            return {};
    }
    // Now select our most favourable entry from maybe.

    // Preference can be fine-tuned via .wanton, see PartialParse::Flaw.
    PartialParse best = maybe.front();
    for (const PartialParse &match : QSpan{maybe}.sliced(1)) {
        if (match.compare(best) < 0)
            best = match;
    }
    return best.results;
}

} // QtParseTemporal

QT_END_NAMESPACE
