qt_commandline_option(gtk TYPE boolean NAME gtk3)
qt_commandline_option(style-windows TYPE boolean)
qt_commandline_option(style-windowsvista TYPE boolean)
qt_commandline_option(style-fusion TYPE boolean)
qt_commandline_option(style-mac TYPE boolean)
qt_commandline_option(style-android TYPE boolean)
