TEMPLATE=subdirs
SUBDIRS=\
   corelib \
   collections \
   exceptionsafety \
   qatomicint \
   qatomicpointer \
   qbitarray \
   qbytearray \
   qbytearraymatcher \
   qcache \
   qchar \
   qcontiguouscache \
   qcoreapplication \
   qcryptographichash \
   qdate \
   qdatetime \
   qeasingcurve \
   qelapsedtimer \
   qexplicitlyshareddatapointer \
   qfreelist \
   qhash \
   qlibrary \
   qline \
   qmap \
   qmargins \
   qmath \
   qmetatype \
   qmutex \
   qmutexlocker \
   qobject \
   qobjectrace \
   qplugin \
   qpluginloader \
   qpoint \
   qqueue \
   qreadlocker \
   qreadwritelock \
   qrect \
   qregexp \
   qringbuffer \
   qscopedpointer \
   qscopedvaluerollback \
   qsemaphore \
   qset \
   qsharedpointer \
   qsignalspy \
   qsize \
   qsizef \
   qstate \
   qstl \
   qstring \
   qstringbuilder1 \
   qstringbuilder2 \
   qstringbuilder3 \
   qstringbuilder4 \
   qstringlist \
   qstringmatcher \
   qstringref \
   qtextboundaryfinder \
   qthread \
   qthreadonce \
   qthreadstorage \
   qtime \
   qtimeline \
   qtimer \
   qtmd5 \
   qtokenautomaton \
   quuid \
   qvarlengtharray \
   qvector \
   qwaitcondition \
   qwineventnotifier \
   qwritelocker \
   selftests \
   utf8
